# Simplified deployment for local testing with lower resource requirements
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dast-orchestrator
  namespace: dast-orchestrator
  labels:
    app: dast-orchestrator
spec:
  replicas: 1  # Single replica for local testing
  selector:
    matchLabels:
      app: dast-orchestrator
  template:
    metadata:
      labels:
        app: dast-orchestrator
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "zap"
        - "zap-scanner"
      containers:
      # ZAP Scanner Container
      - name: zap-scanner
        image: localhost:5000/zap-scanner:latest  # Local registry
        ports:
        - containerPort: 8090
          name: zap-port
        env:
        - name: ZAP_KEY
          valueFrom:
            secretKeyRef:
              name: dast-secrets
              key: ZAP_KEY
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'curl -s -H "X-ZAP-API-Key: $ZAP_KEY" http://localhost:8090/JSON/core/view/version/ > /dev/null'
          initialDelaySeconds: 15
          periodSeconds: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'curl -s -H "X-ZAP-API-Key: $ZAP_KEY" http://localhost:8090/JSON/core/view/version/ > /dev/null'
          initialDelaySeconds: 15
          periodSeconds: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
            
      # DAST API Container  
      - name: dast-api
        image: localhost:5000/dast-api:latest  # Local registry
        ports:
        - containerPort: 8080
          name: api-port
        env:
        # ZAP Configuration (from ConfigMap)
        - name: ZAP_HOST
          valueFrom:
            configMapKeyRef:
              name: dast-config
              key: ZAP_HOST
        - name: ZAP_PORT
          valueFrom:
            configMapKeyRef:
              name: dast-config
              key: ZAP_PORT
        - name: ZAP_PROTO
          valueFrom:
            configMapKeyRef:
              name: dast-config
              key: ZAP_PROTO
        - name: ZAP_KEY
          valueFrom:
            secretKeyRef:
              name: dast-secrets
              key: ZAP_KEY
        # Security
        - name: HMAC_SECRET
          valueFrom:
            secretKeyRef:
              name: dast-secrets
              key: HMAC_SECRET
        # Shared Database configuration (from ConfigMap)
        - name: DB_ENGINE
          valueFrom:
            configMapKeyRef:
              name: dast-config
              key: DB_ENGINE
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dast-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: dast-config
              key: DB_PORT
        - name: DB_CLUSTER
          valueFrom:
            configMapKeyRef:
              name: dast-config
              key: DB_CLUSTER
        # Database RO configuration
        - name: DB_RO_USERNAME
          valueFrom:
            configMapKeyRef:
              name: dast-config
              key: DB_RO_USERNAME
        - name: DB_RO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dast-secrets
              key: DB_RO_PASSWORD
        # Database RW configuration
        - name: DB_RW_USERNAME
          valueFrom:
            configMapKeyRef:
              name: dast-config
              key: DB_RW_USERNAME
        - name: DB_RW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dast-secrets
              key: DB_RW_PASSWORD
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      
      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000

