apiVersion: v1
kind: Service
metadata:
  name: dast-api-service
  namespace: dast-orchestrator
  labels:
    app: dast-orchestrator
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: api
  selector:
    app: dast-orchestrator

---
# NodePort service for local access (no LoadBalancer in local clusters)
apiVersion: v1
kind: Service
metadata:
  name: dast-api-nodeport
  namespace: dast-orchestrator
  labels:
    app: dast-orchestrator
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080  # Access via localhost:30080
    protocol: TCP
    name: http
  selector:
    app: dast-orchestrator

