apiVersion: v1
kind: Service
metadata:
  name: dast-api-service
  namespace: dast-orchestrator
  labels:
    app: dast-orchestrator
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: api
  selector:
    app: dast-orchestrator

---
apiVersion: v1
kind: Service
metadata:
  name: dast-api-loadbalancer
  namespace: dast-orchestrator
  labels:
    app: dast-orchestrator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    app: dast-orchestrator
